spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
      httpclient:
        wiretap: true
        connect-timeout: 1000
        response-timeout: 5s
      httpserver:
        wiretap: true
      routes:
        - id: vcapp-api-instance
          uri: lb://vcapp-api-instance
          predicates:
            - Path=/myvc/**
          filters:
            - CustomAuthFilter
            - name: CircuitBreaker
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack
        - id: demo
          uri: lb://demo
          predicates:
            - Path=/demo/**
          filters:
            - CustomAuthFilter
            - name: Hystrix
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack
        - id: vc-msc
          uri: lb://VC-MSC
          predicates:
            - Path=/msc/**
          filters:
            - RewritePath=/vc_msc/(?<path>.*), /$\{path}
            - CustomAuthFilter
            - name: Hystrix
              args:
                name: vc-api-fallback
                fallbackuri: forward:/vcApiFallBack
                
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://admin:admin@localhost:8761/eureka/
  instance:
    hostname: localhost